### ISSUE TITLE
Reported issue SamsungBrowser traceurRuntime undefined is not a function

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#111]
URL
http://algorithmicassertions.com/quirk#circuit={"cols":[[1,"Y^t"]]}

BROWSER USER AGENT
Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-T560NU Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Safari/537.36

ERROR OBJECT
TypeError: undefined is not a function

ERROR LOCATION
TypeError: undefined is not a function
    at k.$traceurRuntime.createClass.drawOutputSuperpositionDisplay (src.min.js:1523:160)
    at k.$traceurRuntime.createClass.drawOutputDisplays (src.min.js:1521:6)
    at k.$traceurRuntime.createClass.paint (src.min.js:1487:6)
    at i.$traceurRuntime.createClass.paint (src.min.js:1544:127)
    at a.F [as action] (src.min.js:948:35)
    at a.$traceurRuntime.createClass.trigger (src.min.js:386:68)
    at E (src.min.js:944:132)

**Comment by Strilanc** [comment]
This is *probably* Array64Buffer.slice or Array32Buffer.slice, and so fixed by https://github.com/Strilanc/Quirk/commit/f614b472ce294734455c529e5f665ed8386d8f5d

**Comment by Strilanc** [comment]
Confirmed that it's slice by checking the minified code location. Closing with hope.
