### ISSUE TITLE
Reported issue Trident Object doesn't support __$333167720$481339502$__

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#112]
BROWSER USER AGENT
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; LCJB; rv:11.0) like Gecko

ERROR OBJECT
TypeError: Object doesn't support property or method '__$333167720$481339502$__'

ERROR LOCATION
TypeError: Object doesn't support property or method '__$333167720$481339502$__'
at qubitDensityMatrixToBlochVector (src.min.js:1050:20)
at paintBlochSphere (src.min.js:1259:118)
at drawOutputDisplays (src.min.js:1518:93)
at paint (src.min.js:1487:1)
at paint (src.min.js:1544:108)
at F (src.min.js:948:33)
at trigger (src.min.js:386:63)
at E (src.min.js:944:123)
at G (src.min.js:949:62)
at Anonymous function (src.min.js:955:1)

**Comment by Strilanc** [comment]
Fixed by https://github.com/Strilanc/Quirk/commit/f614b472ce294734455c529e5f665ed8386d8f5d

(It was the randomly generated name for Symbol.iterator)
