### ISSUE TITLE
Encountered error: Defaulted to an empty circuit. Failed to understand circuit from URL. (URI malformed)

### ISSUE THREAD

**Issue by Strilanc** [Strilanc/Quirk#181]
(Reported by email)

Defaulted to an empty circuit. Failed to understand circuit from URL.

URL
http://algorithmicassertions.com/quirk#circuit=%7B%22cols%22:%5B%5B1,%22X%22,1,%22X%22%5D,%5B%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22%5D,%5B%22%95%22,1,1,1,%22X%22%5D,%5B1,%22%95%22,1,1,%22X%22%5D,%5B1,1,%22%95%22,1,%22X%22%5D,%5B1,1,1,%22%95%22,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D,%5B1,%7B%22id%22:%22?%22,%22matrix%22:%22%7B%7B-0.534552754290538+0.47104802227963194i,-0.07428673515320268-0.697745365134821i%7D,%7B0.4449053239734092-0.5426106949618321i,-0.18849912386518586-0.6870960389313928i%7D%7D%22%7D%5D,%5B%22%95%22,1,1,1,1,%22X%22%5D,%5B1,%22%95%22,1,1,1,%22X%22%5D,%5B1,1,%22%95%22,1,1,%22X%22%5D,%5B1,1,1,%22%95%22,1,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D%5D%7D

BROWSER
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Netscape
5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

RECOVERY DETAILS
{"document_location_hash": "#circuit=%7B%22cols%22:%5B%5B1,%22X%22,1,%22X%22%5D,%5B%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22%5D,%5B%22%95%22,1,1,1,%22X%22%5D,%5B1,%22%95%22,1,1,%22X%22%5D,%5B1,1,%22%95%22,1,%22X%22%5D,%5B1,1,1,%22%95%22,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D,%5B1,%7B%22id%22:%22?%22,%22matrix%22:%22%7B%7B-0.534552754290538+0.47104802227963194i,-0.07428673515320268-0.697745365134821i%7D,%7B0.4449053239734092-0.5426106949618321i,-0.18849912386518586-0.6870960389313928i%7D%7D%22%7D%5D,%5B%22%95%22,1,1,1,1,%22X%22%5D,%5B1,%22%95%22,1,1,1,%22X%22%5D,%5B1,1,%22%95%22,1,1,%22X%22%5D,%5B1,1,1,%22%95%22,1,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D%5D%7D"}

ERROR OBJECT
URIError: URI malformed

ERROR LOCATION
URIError: URI malformed
    at decodeURIComponent (native)
    at O (src.min.js:1377:37)
    at P (src.min.js:1378:96)
    at src.min.js:1381:103
    at b.g.getUncoatedModule (src.min.js:23:23)
    at Object.r.get [as getModule] (src.min.js:28:51)
    at src.min.js:1990:125

**Comment by Strilanc** [comment]
For some reason, controls "•" were escaped as "%95" instead of "%E2%80%A2".

Fixed link:

algorithmicassertions.com/quirk#circuit=%7B%22cols%22:%5B%5B1,%22X%22,1,%22X%22%5D,%5B%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22,%22Bloch%22%5D,%5B%22%E2%80%A2%22,1,1,1,%22X%22%5D,%5B1,%22%E2%80%A2%22,1,1,%22X%22%5D,%5B1,1,%22%E2%80%A2%22,1,%22X%22%5D,%5B1,1,1,%22%E2%80%A2%22,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D,%5B1,%7B%22id%22:%22?%22,%22matrix%22:%22%7B%7B-0.534552754290538+0.47104802227963194i,-0.07428673515320268-0.697745365134821i%7D,%7B0.4449053239734092-0.5426106949618321i,-0.18849912386518586-0.6870960389313928i%7D%7D%22%7D%5D,%5B%22%E2%80%A2%22,1,1,1,1,%22X%22%5D,%5B1,%22%E2%80%A2%22,1,1,1,%22X%22%5D,%5B1,1,%22%E2%80%A2%22,1,1,%22X%22%5D,%5B1,1,1,%22%E2%80%A2%22,1,%22X%22%5D,%5B%22H%22,%22H%22,%22H%22,%22H%22%5D%5D%7D

**Comment by Strilanc** [comment]
The 'export escaped url' provides a workaround for this issue on the sender side. On the receiver side I'm not comfortable mucking around with UTF8 encodings.

I'm going to close this issue, with the understanding that if I start getting a lot of reports of it then I will put more effort into recovering from single bad characters and trying to infer what was really meant.
